In [1]:
# Dependencies
import pandas as pd

In [2]:
# access crime data and weather data
weather_file_path = "output_data/dc_weather_by_hour.csv"
crime_file_path = "Resources/clean_crime_data.csv"

# create a Pandas DataFrame for each file
weather_df = pd.read_csv(weather_file_path)
crime_df = pd.read_csv(crime_file_path)

In [4]:
# Review sample of weather data
weather_df.head()

,Date_ID,date,hour,maxtemp_f,mintemp_f,avgtemp_f,totalprecip_in,avghumidity,day_condition,hour_temp_f,hour_condition,hour_precip_in,hour_humidity
0,0,2022-02-06,12:00AM,40.5,24.1,32.8,0.0,52.0,Sunny,26.4,Clear,0.0,52
1,1,2022-02-06,1:00AM,40.5,24.1,32.8,0.0,52.0,Sunny,26.1,Clear,0.0,52
2,2,2022-02-06,2:00AM,40.5,24.1,32.8,0.0,52.0,Sunny,25.8,Clear,0.0,53
3,3,2022-02-06,3:00AM,40.5,24.1,32.8,0.0,52.0,Sunny,25.5,Clear,0.0,53
4,4,2022-02-06,4:00AM,40.5,24.1,32.8,0.0,52.0,Sunny,25.0,Clear,0.0,55

In [5]:
# Review sample of crime data
crime_df.head()

,Unnamed: 0,YEAR,START_DATE,offensegroup,OFFENSE,offense-text,offensekey,START_TIME
0,0,2022,2017-06-09,violent,homicide,homicide,violent|homicide,00:20:00
1,1,2021,2021-02-11,property,theft/other,theft/other,property|theft/other,15:00:52
2,2,2021,2021-02-11,violent,robbery,robbery,violent|robbery,18:03:44
3,3,2021,2021-02-12,violent,robbery,robbery,violent|robbery,05:09:33
4,4,2021,2021-02-18,violent,robbery,robbery,violent|robbery,04:39:52

In [6]:
# Convert crime date type to match weather date type
crime_df['START_DATE'] = pd.to_datetime(crime_df['START_DATE'], format='%Y/%m/%d').dt.strftime('%Y-%m-%d')
# Check sample to see results
crime_df.head()

,Unnamed: 0,YEAR,START_DATE,offensegroup,OFFENSE,offense-text,offensekey,START_TIME
0,0,2022,2017-06-09,violent,homicide,homicide,violent|homicide,00:20:00
1,1,2021,2021-02-11,property,theft/other,theft/other,property|theft/other,15:00:52
2,2,2021,2021-02-11,violent,robbery,robbery,violent|robbery,18:03:44
3,3,2021,2021-02-12,violent,robbery,robbery,violent|robbery,05:09:33
4,4,2021,2021-02-18,violent,robbery,robbery,violent|robbery,04:39:52

In [7]:
# Parse out hour from START_TIME
crime_df[['START_HOUR','START_MIN_SEC']] = crime_df['START_TIME'].str.split(':',n=1,expand=True)
crime_df.head()

,Unnamed: 0,YEAR,START_DATE,offensegroup,OFFENSE,offense-text,offensekey,START_TIME,START_HOUR,START_MIN_SEC
0,0,2022,2017-06-09,violent,homicide,homicide,violent|homicide,00:20:00,00,20:00
1,1,2021,2021-02-11,property,theft/other,theft/other,property|theft/other,15:00:52,15,00:52
2,2,2021,2021-02-11,violent,robbery,robbery,violent|robbery,18:03:44,18,03:44
3,3,2021,2021-02-12,violent,robbery,robbery,violent|robbery,05:09:33,05,09:33
4,4,2021,2021-02-18,violent,robbery,robbery,violent|robbery,04:39:52,04,39:52

In [8]:
# Create an hour list based on 'START_HOUR' to match 00:00AM/PM weather hour format
# Make a list out of 'START_HOUR' column.
hour_num_list = crime_df["START_HOUR"].values.tolist()

# Create a new list for the hours
hour_list = []

# Iterate over the 'START_HOUR' column to create hour list.
for hour in hour_num_list:
    if hour == "00":
        hour_list.append("12:00AM")
    elif hour == "01":
        hour_list.append("1:00AM")
    elif hour == "02":
        hour_list.append("2:00AM")
    elif hour == "03":
        hour_list.append("3:00AM")
    elif hour == "04":
        hour_list.append("4:00AM")
    elif hour == "05":
        hour_list.append("5:00AM")
    elif hour == "06":
        hour_list.append("6:00AM")
    elif hour == "07":
        hour_list.append("7:00AM")
    elif hour == "08":
        hour_list.append("8:00AM")
    elif hour == "09":
        hour_list.append("9:00AM")
    elif hour == "10":
        hour_list.append("10:00AM")
    elif hour == "11":
        hour_list.append("11:00AM")
    elif hour == "12":
        hour_list.append("12:00PM")
    elif hour == "13":
        hour_list.append("1:00PM")
    elif hour == "14":
        hour_list.append("2:00PM")
    elif hour == "15":
        hour_list.append("3:00PM")
    elif hour == "16":
        hour_list.append("4:00PM")
    elif hour == "17":
        hour_list.append("5:00PM")
    elif hour == "18":
        hour_list.append("6:00PM")
    elif hour == "19":
        hour_list.append("7:00PM")
    elif hour == "20":
        hour_list.append("8:00PM")
    elif hour == "21":
        hour_list.append("9:00PM")
    elif hour == "22":
        hour_list.append("10:00PM")
    elif hour == "23":
        hour_list.append("11:00PM")

# Add new hour list to DataFrame
crime_df['Hour'] = hour_list
crime_df.head()

,Unnamed: 0,YEAR,START_DATE,offensegroup,OFFENSE,offense-text,offensekey,START_TIME,START_HOUR,START_MIN_SEC,Hour
0,0,2022,2017-06-09,violent,homicide,homicide,violent|homicide,00:20:00,00,20:00,12:00AM
1,1,2021,2021-02-11,property,theft/other,theft/other,property|theft/other,15:00:52,15,00:52,3:00PM
2,2,2021,2021-02-11,violent,robbery,robbery,violent|robbery,18:03:44,18,03:44,6:00PM
3,3,2021,2021-02-12,violent,robbery,robbery,violent|robbery,05:09:33,05,09:33,5:00AM
4,4,2021,2021-02-18,violent,robbery,robbery,violent|robbery,04:39:52,04,39:52,4:00AM

In [9]:
crime_df = crime_df[['YEAR','START_DATE','START_TIME','Hour','offensegroup','OFFENSE','offense-text']]
crime_df.head()

   YEAR  START_DATE START_TIME     Hour offensegroup      OFFENSE offense-text
0  2022  2017-06-09   00:20:00  12:00AM      violent     homicide     homicide
1  2021  2021-02-11   15:00:52   3:00PM     property  theft/other  theft/other
2  2021  2021-02-11   18:03:44   6:00PM      violent      robbery      robbery
3  2021  2021-02-12   05:09:33   5:00AM      violent      robbery      robbery
4  2021  2021-02-18   04:39:52   4:00AM      violent      robbery      robbery

In [10]:
# Merge crime dataframe with weather dataframe
crime_weather = pd.merge(crime_df, weather_df, how='left', left_on=['START_DATE','Hour'], right_on=['date','hour'])
# Remove all rows outside of date range
crime_weather.dropna(how='any', inplace=True)
# Sort by start date and time
crime_weather.sort_values(["date", "START_TIME"], ascending=True, inplace=True)
# Reset Index
crime_weather.reset_index(drop=True, inplace=True)
# Remove redundant and unnecessary columns
crime_weather = crime_weather[['YEAR', 'START_DATE', 'START_TIME', 'Hour', 'offensegroup', 'OFFENSE',
       'offense-text','maxtemp_f', 'mintemp_f','avgtemp_f', 'totalprecip_in', 'avghumidity', 'day_condition',
       'hour_temp_f', 'hour_condition', 'hour_precip_in', 'hour_humidity']]
# Rename columns for cleaner presentation
crime_weather.rename(columns={"YEAR": "Year", "START_DATE": "Start Date", "START_TIME": "Start Time",
                    "offensegroup": "Offense Group", 'OFFENSE': 'Offense', 'offense-text': 'Offense Text',
                    'maxtemp_f': 'Max Temp (f)', 'mintemp_f': 'Min Temp (f)', 'avgtemp_f': 'Avg Temp (f)',
                    'totalprecip_in': 'Total Precipitation (in)', 'avghumidity': 'Avg Humidity (%)',
                    'day_condition': 'Day Condition', 'hour_temp_f': 'Hour Temp (f)', 'hour_condition': 'Hour Condition',
                    'hour_precip_in': 'Hour Precipitation (in)','hour_humidity': 'Hour Humidity (%)'}, inplace=True)
# View results
crime_weather

,Year,Start Date,Start Time,Hour,Offense Group,Offense,Offense Text,Max Temp (f),Min Temp (f),Avg Temp (f),Total Precipitation (in),Avg Humidity (%),Day Condition,Hour Temp (f),Hour Condition,Hour Precipitation (in),Hour Humidity (%)
0,2022,2022-02-06,00:12:00,12:00AM,violent,robbery,robbery,40.5,24.1,32.8,0.0,52.0,Sunny,26.4,Clear,0.0,52.0
1,2022,2022-02-06,00:19:00,12:00AM,property,theft/other,theft/other,40.5,24.1,32.8,0.0,52.0,Sunny,26.4,Clear,0.0,52.0
2,2022,2022-02-06,01:00:00,1:00AM,property,motor vehicle theft,motor vehicle theft,40.5,24.1,32.8,0.0,52.0,Sunny,26.1,Clear,0.0,52.0
3,2022,2022-02-06,01:30:00,1:00AM,property,theft/other,theft/other,40.5,24.1,32.8,0.0,52.0,Sunny,26.1,Clear,0.0,52.0
4,2022,2022-02-06,02:45:00,2:00AM,violent,robbery,robbery,40.5,24.1,32.8,0.0,52.0,Sunny,25.8,Clear,0.0,53.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27556,2023,2023-02-05,23:00:00,11:00PM,violent,assault w/dangerous weapon,assault w/dangerous weapon,50.9,30.0,41.1,0.0,61.0,Overcast,42.5,Mist,0.0,95.0
27557,2023,2023-02-05,23:00:00,11:00PM,property,theft f/auto,theft f/auto,50.9,30.0,41.1,0.0,61.0,Overcast,42.5,Mist,0.0,95.0
27558,2023,2023-02-05,23:21:00,11:00PM,property,theft f/auto,theft f/auto,50.9,30.0,41.1,0.0,61.0,Overcast,42.5,Mist,0.0,95.0
27559,2023,2023-02-05,23:40:00,11:00PM,property,motor vehicle theft,motor vehicle theft,50.9,30.0,41.1,0.0,61.0,Overcast,42.5,Mist,0.0,95.0
27560,2023,2023-02-05,23:55:00,11:00PM,property,theft f/auto,theft f/auto,50.9,30.0,41.1,0.0,61.0,Overcast,42.5,Mist,0.0,95.0

In [11]:
# Export the merged dataframe
crime_weather.to_csv("output_data/crime_weather_merged.csv", index_label="ID")